input {
  file {
    path => "/usr/share/logstash/data/*.log"
    start_position => "end"
    sincedb_path => "/usr/share/logstash/sincedb/sincedb"
    codec => "json"
    mode => "tail"
  }
}

filter {
  mutate {
    add_field => {
      "poc_name" => "mini-elastic-observability-siem-poc"
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "mini-elastic-logs-%{+YYYY.MM.dd}"
  }

  stdout {
    codec => rubydebug
  }
}